#!/usr/bin/env python3
"""
WebScan Pro - HTML Report Generator
Converts JSON scan results into a professional HTML report.
"""

import json
import sys
from datetime import datetime
from pathlib import Path


SEVERITY_COLORS = {
    "CRITICAL": "#FF2D55",
    "HIGH": "#FF6B35",
    "MEDIUM": "#FFD60A",
    "LOW": "#30D158",
    "INFO": "#0A84FF"
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WebScan Pro – Security Report</title>
<style>
  :root {{
    --bg: #0a0a0f;
    --surface: #12121a;
    --border: #1e1e2e;
    --text: #e2e8f0;
    --muted: #64748b;
    --accent: #00d4ff;
    --critical: #FF2D55;
    --high: #FF6B35;
    --medium: #FFD60A;
    --low: #30D158;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Courier New', monospace; padding: 2rem; }}
  .header {{ border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
  .header h1 {{ color: var(--accent); font-size: 2rem; letter-spacing: 0.2em; }}
  .header p {{ color: var(--muted); margin-top: 0.5rem; }}
  .meta-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .meta-card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; }}
  .meta-card .label {{ color: var(--muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em; }}
  .meta-card .value {{ color: var(--accent); font-size: 1.25rem; font-weight: bold; margin-top: 0.25rem; }}
  .severity-bar {{ display: flex; gap: 1rem; margin-bottom: 2rem; }}
  .sev-pill {{ padding: 0.4rem 1rem; border-radius: 20px; font-size: 0.85rem; font-weight: bold; }}
  .sev-CRITICAL {{ background: rgba(255,45,85,0.2); color: var(--critical); border: 1px solid var(--critical); }}
  .sev-HIGH {{ background: rgba(255,107,53,0.2); color: var(--high); border: 1px solid var(--high); }}
  .sev-MEDIUM {{ background: rgba(255,214,10,0.2); color: var(--medium); border: 1px solid var(--medium); }}
  .sev-LOW {{ background: rgba(48,209,88,0.2); color: var(--low); border: 1px solid var(--low); }}
  h2 {{ color: var(--accent); border-left: 3px solid var(--accent); padding-left: 1rem; margin-bottom: 1rem; }}
  .finding {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; margin-bottom: 1rem; }}
  .finding-header {{ display: flex; align-items: center; gap: 1rem; margin-bottom: 0.75rem; }}
  .finding h3 {{ color: var(--text); font-size: 1rem; }}
  .finding .url {{ color: var(--muted); font-size: 0.8rem; margin-bottom: 0.5rem; word-break: break-all; }}
  .finding .desc {{ color: #94a3b8; font-size: 0.875rem; line-height: 1.6; }}
  .finding .rec {{ color: #30D158; font-size: 0.8rem; margin-top: 0.5rem; }}
  .finding .payload {{ background: #0f0f17; border: 1px solid var(--border); border-radius: 4px; padding: 0.5rem; font-size: 0.8rem; color: #FFD60A; margin-top: 0.5rem; word-break: break-all; }}
  footer {{ margin-top: 3rem; text-align: center; color: var(--muted); font-size: 0.75rem; border-top: 1px solid var(--border); padding-top: 1.5rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>⚡ WEBSCAN PRO</h1>
  <p>Web Application Vulnerability Assessment Report</p>
  <p style="margin-top:0.5rem; color:#94a3b8">Target: <span style="color:var(--accent)">{target}</span> &nbsp;|&nbsp; Generated: {generated}</p>
</div>

<div class="meta-grid">
  <div class="meta-card">
    <div class="label">Risk Score</div>
    <div class="value" style="color:{risk_color}">{risk_score}</div>
  </div>
  <div class="meta-card">
    <div class="label">Total Findings</div>
    <div class="value">{total_findings}</div>
  </div>
  <div class="meta-card">
    <div class="label">Scan Duration</div>
    <div class="value">{duration}s</div>
  </div>
  <div class="meta-card">
    <div class="label">Server</div>
    <div class="value" style="font-size:0.9rem">{server}</div>
  </div>
</div>

<div class="severity-bar">
  <span class="sev-pill sev-CRITICAL">CRITICAL: {critical}</span>
  <span class="sev-pill sev-HIGH">HIGH: {high}</span>
  <span class="sev-pill sev-MEDIUM">MEDIUM: {medium}</span>
  <span class="sev-pill sev-LOW">LOW: {low}</span>
</div>

<h2>Vulnerability Findings</h2>
{findings_html}

<footer>
  Generated by WebScan Pro v1.0.0 &nbsp;|&nbsp; For authorized security testing only &nbsp;|&nbsp; {generated}
</footer>
</body>
</html>"""


def severity_to_color(sev: str) -> str:
    return SEVERITY_COLORS.get(sev, "#64748b")


def risk_to_color(score: int) -> str:
    if score >= 20:
        return "#FF2D55"
    elif score >= 10:
        return "#FF6B35"
    elif score >= 5:
        return "#FFD60A"
    return "#30D158"


def render_finding(f: dict) -> str:
    sev = f.get("severity", "INFO")
    color = severity_to_color(sev)
    payload_html = ""
    if "payload" in f:
        payload_html = f'<div class="payload">Payload: {f["payload"]}</div>'
    issues_html = ""
    if "issues" in f:
        issues_html = f'<div class="desc">Issues: {", ".join(f["issues"])}</div>'

    return f"""
<div class="finding">
  <div class="finding-header">
    <span class="sev-pill sev-{sev}" style="min-width:90px;text-align:center">{sev}</span>
    <h3>{f.get("type", "Unknown")}</h3>
  </div>
  <div class="url">URL: {f.get("url", "N/A")}</div>
  <div class="desc">{f.get("description", "")}</div>
  {issues_html}
  {payload_html}
  <div class="rec">✓ Recommendation: {f.get("recommendation", "Review and remediate.")}</div>
</div>"""


def generate_html_report(json_path: str, output_path: str = None):
    with open(json_path) as f:
        report = json.load(f)

    meta = report["report_metadata"]
    info = report.get("target_info", {})
    findings = report.get("findings", [])
    sev_summary = meta.get("severity_summary", {})

    findings_html = "".join(render_finding(f) for f in findings)
    if not findings_html:
        findings_html = '<p style="color:#64748b">No vulnerabilities detected.</p>'

    html = HTML_TEMPLATE.format(
        target=meta.get("scan_target", "Unknown"),
        generated=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        risk_score=meta.get("risk_score", 0),
        risk_color=risk_to_color(meta.get("risk_score", 0)),
        total_findings=meta.get("total_findings", 0),
        duration=meta.get("duration_seconds", 0),
        server=info.get("server", "Unknown"),
        critical=sev_summary.get("CRITICAL", 0),
        high=sev_summary.get("HIGH", 0),
        medium=sev_summary.get("MEDIUM", 0),
        low=sev_summary.get("LOW", 0),
        findings_html=findings_html
    )

    if not output_path:
        output_path = json_path.replace(".json", ".html")

    with open(output_path, "w") as f:
        f.write(html)

    print(f"[+] HTML report saved: {output_path}")
    return output_path


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python report_generator.py <scan_report.json> [output.html]")
        sys.exit(1)

    out = sys.argv[2] if len(sys.argv) > 2 else None
    generate_html_report(sys.argv[1], out)
